-- local conform = require("conform")
-- conform.setup({
-- 	-- [Formatters list](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#formatters)
-- 	-- :h conform-formatters
-- 	formatters_by_ft = {
-- 		lua = { "stylua" },
-- 		python = { "isort", "black" },
-- 		rust = { "rustfmt" },
-- 		dart = { "dart_format" },
-- 		-- c = { "clangformat" },
-- 		-- cpp = { "clangformat" },
-- 	},
-- 	format_on_save = {
-- 		timeout_ms = 500,
-- 		lsp_format = "fallback",
-- 	},
-- })
